server:
  port: 8000
spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    config:
      enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
  instance:
    prefer-ip-address: true

