server:
  port: 8081
spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:h2:mem:inventory-db
  h2:
    console:
      enabled: true
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
  instance:
    prefer-ip-address: true
