server:
  port: 8081
spring:
  application:
    name=inventory-service
  datasource:
    url: jdbc:h2:mem:inventory-db
  h2:
    console:
      enabled: true
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false


